name: SB
channels:
  - pyg
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - biopython=1.79
  - blas=1.0
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - cairo=1.18.0
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - colorama=0.4.6
  - contourpy=1.3.2
  - cpython=3.10.19
  - cuda-cudart=12.4.127
  - cuda-cudart_linux-64=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.4.127
  - cuda-runtime=12.4.1
  - cuda-version=12.4
  - cycler=0.12.1
  - filelock=3.20.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.61.0
  - freetype=2.14.1
  - freetype-py=2.3.0
  - fsspec=2025.10.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - greenlet=3.2.4
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=73.2
  - idna=3.11
  - imageio=2.37.0
  - intel-openmp=2022.1.0
  - jinja2=3.1.6
  - kiwisolver=1.4.9
  - lcms2=2.17
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - libblas=3.9.0
  - libboost=1.82.0
  - libboost-python=1.82.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.9.0
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.9.1.3
  - libcurand=10.3.5.147
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libdeflate=1.25
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.86.2
  - libgomp=15.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnpp=12.2.5.30
  - libnsl=2.0.1
  - libnvfatbin=12.4.127
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libpng=1.6.51
  - libsqlite=3.51.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libuuid=2.41.2
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.12.7
  - libzlib=1.3.1
  - lightning-utilities=0.15.2
  - llvm-openmp=15.0.7
  - markupsafe=3.0.3
  - matplotlib-base=3.10.8
  - meeko=0.7.1
  - mkl=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - ncurses=6.5
  - networkx=3.4.2
  - numpy=1.26.4
  - ocl-icd=2.3.3
  - openbabel=3.1.1
  - opencl-headers=2025.06.13
  - openjpeg=2.5.4
  - openssl=3.6.0
  - packaging=25.0
  - pandas=2.2.3
  - pcre2=10.47
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - prody=2.6.1
  - pthread-stubs=0.4
  - pycairo=1.27.0
  - pycparser=2.22
  - pyparsing=3.1.1
  - pysocks=1.7.1
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytorch=2.4.1
  - pytorch-cuda=12.4
  - pytorch-lightning=2.5.5
  - pytorch-mutex=1.0
  - pytorch-scatter=2.1.2
  - pytz=2025.2
  - pyyaml=6.0.3
  - qhull=2020.2
  - readline=8.2
  - reportlab=4.4.5
  - requests=2.32.5
  - rlpycairo=0.4.0
  - scipy=1.13.1
  - setuptools=80.9.0
  - six=1.17.0
  - sqlalchemy=2.0.44
  - sympy=1.14.0
  - tk=8.6.13
  - torchmetrics=1.8.2
  - torchtriton=3.0.0
  - tqdm=4.67.1
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - unicodedata2=17.0.0
  - urllib3=2.5.0
  - wheel=0.45.1
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zlib=1.3.1
  - zlib-ng=2.3.2
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - annotated-types==0.7.0
      - blinker==1.9.0
      - click==8.3.1
      - dnspython==2.8.0
      - email-validator==2.3.0
      - flask==3.1.2
      - flask-sqlalchemy==3.1.1
      - gemmi==0.7.4
      - gitdb==4.0.12
      - gitpython==3.1.45
      - gunicorn==23.0.0
      - itsdangerous==2.2.0
      - markdown-it-py==4.0.0
      - mdurl==0.1.2
      - molscrub==0.2.2
      - platformdirs==4.5.0
      - protobuf==6.33.1
      - psycopg2-binary==2.9.11
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - rdkit==2025.9.2
      - rich==14.2.0
      - sentry-sdk==2.46.0
      - smmap==5.0.2
      - typing-inspection==0.4.2
      - vina==1.2.7
      - wandb==0.23.1
      - werkzeug==3.1.4
