name: SB
channels:
  - pyg
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - biopython=1.79=py310h5764c6d_3
  - blas=1.0=mkl
  - brotli=1.2.0=hed03a55_1
  - brotli-bin=1.2.0=hb03c661_1
  - brotli-python=1.2.0=py310hba01987_1
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.0=hbb29018_2
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py310he7384ee_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.2=py310h3788b33_0
  - cpython=3.10.19=py310hd8ed1ab_2
  - cuda-cudart=12.4.127=he02047a_2
  - cuda-cudart_linux-64=12.4.127=h85509e4_2
  - cuda-cupti=12.4.127=he02047a_2
  - cuda-libraries=12.4.1=ha770c72_1
  - cuda-nvrtc=12.4.127=he02047a_2
  - cuda-nvtx=12.4.127=he02047a_2
  - cuda-opencl=12.4.127=he02047a_1
  - cuda-runtime=12.4.1=ha804496_0
  - cuda-version=12.4=h3060b56_3
  - cycler=0.12.1=pyhcf101f3_2
  - filelock=3.20.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.0=py310h3406613_0
  - freetype=2.14.1=ha770c72_0
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - fsspec=2025.10.0=pyhd8ed1ab_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py310h63ebcad_2
  - greenlet=3.2.4=py310hea6c23e_1
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - idna=3.11=pyhd8ed1ab_0
  - imageio=2.37.0=pyhfb79c49_0
  - intel-openmp=2022.1.0=h9e868ea_3769
  - jinja2=3.1.6=pyhcf101f3_1
  - kiwisolver=1.4.9=py310haaf941d_2
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - lerc=4.0.0=h0aef613_1
  - libblas=3.9.0=16_linux64_mkl
  - libboost=1.82.0=h6fcfa73_6
  - libboost-python=1.82.0=py310hcb52e73_6
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libcblas=3.9.0=16_linux64_mkl
  - libcublas=12.4.5.8=he02047a_2
  - libcufft=11.2.1.3=he02047a_2
  - libcufile=1.9.1.3=he02047a_2
  - libcurand=10.3.5.147=he02047a_2
  - libcusolver=11.6.1.9=he02047a_2
  - libcusparse=12.3.1.170=he02047a_2
  - libdeflate=1.25=h17f619e_0
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_14
  - libgcc-ng=15.2.0=h69a702a_14
  - libgfortran=15.2.0=h69a702a_14
  - libgfortran-ng=15.2.0=h69a702a_14
  - libgfortran5=15.2.0=h68bc16d_14
  - libglib=2.86.2=h6548e54_1
  - libgomp=15.2.0=he0feb66_14
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.9.0=16_linux64_mkl
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnpp=12.2.5.30=he02047a_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libnvfatbin=12.4.127=he02047a_2
  - libnvjitlink=12.4.127=he02047a_2
  - libnvjpeg=12.3.1.117=he02047a_2
  - libpng=1.6.51=h421ea60_0
  - libsqlite=3.51.1=h0c1763c_0
  - libstdcxx=15.2.0=h934c35e_14
  - libstdcxx-ng=15.2.0=hdf11a46_14
  - libtiff=4.7.1=h9d88235_1
  - libuuid=2.41.2=he9a06e4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.7=h4c95cb1_3
  - libzlib=1.3.1=hb9d3cd8_2
  - lightning-utilities=0.15.2=pyhd8ed1ab_0
  - llvm-openmp=15.0.7=h0cdce71_0
  - markupsafe=3.0.3=py310h3406613_0
  - matplotlib-base=3.10.8=py310hfde16b3_0
  - meeko=0.7.1=pyhd8ed1ab_0
  - mkl=2022.1.0=hc2b9512_224
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - networkx=3.4.2=pyh267e887_2
  - numpy=1.26.4=py310hb13e2d6_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - openbabel=3.1.1=py310hbff9852_9
  - opencl-headers=2025.06.13=h5888daf_0
  - openjpeg=2.5.4=h55fea9a_0
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.2.3=py310h5eaa309_3
  - pcre2=10.47=haa7fec5_0
  - pillow=12.0.0=py310h5a73078_2
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - prody=2.6.1=py310h9d64cdd_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pycairo=1.27.0=py310h25ff670_0
  - pycparser=2.22=pyh29332c3_1
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.19=h3c07f61_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytorch=2.4.1=py3.10_cuda12.4_cudnn9.1.0_0
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-lightning=2.5.5=pyh2a12c56_0
  - pytorch-mutex=1.0=cuda
  - pytorch-scatter=2.1.2=py310_torch_2.4.0_cu124
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py310h3406613_0
  - qhull=2020.2=h434a139_5
  - readline=8.2=h8c095d6_2
  - reportlab=4.4.5=py310h7c4b9e2_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rlpycairo=0.4.0=pyh6c17108_0
  - scipy=1.13.1=py310h93e2701_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sqlalchemy=2.0.44=py310h7c4b9e2_0
  - sympy=1.14.0=pyh2585a3b_105
  - tk=8.6.13=noxft_ha0e22de_103
  - torchmetrics=1.8.2=pyhd8ed1ab_0
  - torchtriton=3.0.0=py310
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - unicodedata2=17.0.0=py310h7c4b9e2_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h280c20c_3
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.3.2=h54a6638_0
  - zstandard=0.25.0=py310h139afa4_1
  - zstd=1.5.7=h3691f8a_5
  - pip:
      - annotated-types==0.7.0
      - blinker==1.9.0
      - click==8.3.1
      - dnspython==2.8.0
      - email-validator==2.3.0
      - flask==3.1.2
      - flask-sqlalchemy==3.1.1
      - gemmi==0.7.4
      - gitdb==4.0.12
      - gitpython==3.1.45
      - gunicorn==23.0.0
      - itsdangerous==2.2.0
      - markdown-it-py==4.0.0
      - mdurl==0.1.2
      - molscrub==0.2.2
      - platformdirs==4.5.0
      - protobuf==6.33.1
      - psycopg2-binary==2.9.11
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - rdkit==2025.9.2
      - rich==14.2.0
      - sentry-sdk==2.46.0
      - smmap==5.0.2
      - typing-inspection==0.4.2
      - vina==1.2.7
      - wandb==0.23.1
      - werkzeug==3.1.4
